# Kernel / threads
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_THREAD_STACK_INFO=y

# Logs / console
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y

# ZBUS
CONFIG_ZBUS=y

# Gerador de número aleatório genérico (para sys_rand32_get)
CONFIG_TEST_RANDOM_GENERATOR=y
